### ISSUE TITLE
upload requires https connection

### ISSUE THREAD

**Issue by smoh** [mfouesneau/tap#2]
Hi, thanks for making this tutorial available.

One thing I noticed trying to upload my table is that once you are logged in, if you try to upload table to `http://...`, it fails with 500 internal server error (with message that you need to be logged in to upload) and you get logged out (i.e., `gaia.session` is changed). It seems to work fine once I change to https. Just thought it's worth pointing out.

**Comment by mfouesneau** [comment]
I added a protocol handler. I only use https on GaiaArchive but any can switch. Let me know if that works.

**Comment by smoh** [comment]
Yes, I think it's fixed now. Thanks.

**Comment by mfouesneau** [comment]
Thanks for checking.

**Comment by smoh** [comment]
argh, maybe I wasn't careful, because I can't get it to work now.
[Here](https://gist.github.com/smoh/334633ed5ae9614fbd6fa422b2a16edc)'s my various testing attempts -- I find various issues as you can see.. I cannot tell exactly what the problem is.

(apologies for the mess, pushed a wrong button)

**Comment by mfouesneau** [comment]
Testing needed after our debugging session

**Comment by smoh** [comment]
Everything on the notebook linked works now. Awesome, thanks much!
